language: node_js
node_js:
  - 14
  
services:
  - docker

install:
  - docker-compose up -d nginx

script:
  - docker ps | grep nginx
  - docker ps | grep webapp
  - curl localhost:80
  - curl localhost:4000