version: '3.1'
services:
  nginx:
    image: nginx:1.19
    container_name: nginx
    depends_on:
      - webapp
    volumes:
      - ./conf.d/default:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - my-network
      
  webapp:
    build :
      context: ./
      dockerfile: Dockerfile
    image: webapp
    container_name: webapp
    depends_on:
      - mongo
    environment:
      - WEB_APP=app.js
    env_file: .env
    command: npm run start
    networks:
      my-network:
        aliases:
            - web-app
    ports:
      - 3000:3000

  mongo:
    container_name: mongobackend
    image: mongo
    networks:
      - my-network
    expose:
        - "27017"
    ports:
        - "27017:27017"
    volumes:
        - mydb:/data/db

volumes:
  mydb:

networks:
  my-network: